version: '3.8'

services:
  # 2. The Core Backend (Node.js)
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - PORT=8000
      - MONGO_URL=mongodb://mongo:27017/blog_db
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}         # Will read from your .env
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET} # Will read from your .env
      - GOOGLE_CALLBACK_URL=http://localhost:5173   # Match frontend
    depends_on:
      - mongo
    networks:
      - app_network

  # 3. Infrastructure (Databases)

  mongo:
    image: mongo:latest
    networks:
      - app_network

networks:
  app_network:
    driver: bridge