version: '3.8'

services:
  backend:
    container_name: blog_backend
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    volumes:
      - ./.env:/app/.env:ro
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - PORT=8000
      - MONGO_URL=${MONGO_URL}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL}
      - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
      - OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
      - R2_BUCKET_NAME=${R2_BUCKET_NAME}
      - R2_ACCOUNT_ID=${R2_ACCOUNT_ID}
      - R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
      - R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
      - R2_DEVURL=${R2_DEVURL}
      - RESEND_API_KEY=${RESEND_API_KEY}
    networks:
      - app_network

networks:
  app_network:
    driver: bridge