// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: analytics.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PostStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	TimeRange     string                 `protobuf:"bytes,2,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"` // "24h", "7d", "30d", "all"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostStatsRequest) Reset() {
	*x = PostStatsRequest{}
	mi := &file_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostStatsRequest) ProtoMessage() {}

func (x *PostStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostStatsRequest.ProtoReflect.Descriptor instead.
func (*PostStatsRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *PostStatsRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *PostStatsRequest) GetTimeRange() string {
	if x != nil {
		return x.TimeRange
	}
	return ""
}

type PostStatsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Views          int64                  `protobuf:"varint,1,opt,name=views,proto3" json:"views,omitempty"`
	UniqueVisitors int64                  `protobuf:"varint,2,opt,name=unique_visitors,json=uniqueVisitors,proto3" json:"unique_visitors,omitempty"`
	AvgReadTimeSec float64                `protobuf:"fixed64,3,opt,name=avg_read_time_sec,json=avgReadTimeSec,proto3" json:"avg_read_time_sec,omitempty"`
	ChartData      []*TimeSeriesPoint     `protobuf:"bytes,4,rep,name=chart_data,json=chartData,proto3" json:"chart_data,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PostStatsResponse) Reset() {
	*x = PostStatsResponse{}
	mi := &file_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostStatsResponse) ProtoMessage() {}

func (x *PostStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostStatsResponse.ProtoReflect.Descriptor instead.
func (*PostStatsResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *PostStatsResponse) GetViews() int64 {
	if x != nil {
		return x.Views
	}
	return 0
}

func (x *PostStatsResponse) GetUniqueVisitors() int64 {
	if x != nil {
		return x.UniqueVisitors
	}
	return 0
}

func (x *PostStatsResponse) GetAvgReadTimeSec() float64 {
	if x != nil {
		return x.AvgReadTimeSec
	}
	return 0
}

func (x *PostStatsResponse) GetChartData() []*TimeSeriesPoint {
	if x != nil {
		return x.ChartData
	}
	return nil
}

type AuthorStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorId      string                 `protobuf:"bytes,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	TimeRange     string                 `protobuf:"bytes,2,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorStatsRequest) Reset() {
	*x = AuthorStatsRequest{}
	mi := &file_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorStatsRequest) ProtoMessage() {}

func (x *AuthorStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorStatsRequest.ProtoReflect.Descriptor instead.
func (*AuthorStatsRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *AuthorStatsRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *AuthorStatsRequest) GetTimeRange() string {
	if x != nil {
		return x.TimeRange
	}
	return ""
}

type AuthorStatsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TotalViews         int64                  `protobuf:"varint,1,opt,name=total_views,json=totalViews,proto3" json:"total_views,omitempty"`
	TotalVisitors      int64                  `protobuf:"varint,2,opt,name=total_visitors,json=totalVisitors,proto3" json:"total_visitors,omitempty"`
	OverallAvgReadTime float64                `protobuf:"fixed64,3,opt,name=overall_avg_read_time,json=overallAvgReadTime,proto3" json:"overall_avg_read_time,omitempty"`
	// A list of the author's best performing content
	TopPosts      []*TopPost `protobuf:"bytes,4,rep,name=top_posts,json=topPosts,proto3" json:"top_posts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorStatsResponse) Reset() {
	*x = AuthorStatsResponse{}
	mi := &file_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorStatsResponse) ProtoMessage() {}

func (x *AuthorStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorStatsResponse.ProtoReflect.Descriptor instead.
func (*AuthorStatsResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *AuthorStatsResponse) GetTotalViews() int64 {
	if x != nil {
		return x.TotalViews
	}
	return 0
}

func (x *AuthorStatsResponse) GetTotalVisitors() int64 {
	if x != nil {
		return x.TotalVisitors
	}
	return 0
}

func (x *AuthorStatsResponse) GetOverallAvgReadTime() float64 {
	if x != nil {
		return x.OverallAvgReadTime
	}
	return 0
}

func (x *AuthorStatsResponse) GetTopPosts() []*TopPost {
	if x != nil {
		return x.TopPosts
	}
	return nil
}

type TopPost struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"` // Optional: Fetch from main DB or store here
	Views         int64                  `protobuf:"varint,3,opt,name=views,proto3" json:"views,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopPost) Reset() {
	*x = TopPost{}
	mi := &file_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopPost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopPost) ProtoMessage() {}

func (x *TopPost) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopPost.ProtoReflect.Descriptor instead.
func (*TopPost) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *TopPost) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *TopPost) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TopPost) GetViews() int64 {
	if x != nil {
		return x.Views
	}
	return 0
}

type TimeSeriesPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Views         int64                  `protobuf:"varint,2,opt,name=views,proto3" json:"views,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeSeriesPoint) Reset() {
	*x = TimeSeriesPoint{}
	mi := &file_analytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSeriesPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSeriesPoint) ProtoMessage() {}

func (x *TimeSeriesPoint) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSeriesPoint.ProtoReflect.Descriptor instead.
func (*TimeSeriesPoint) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{5}
}

func (x *TimeSeriesPoint) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *TimeSeriesPoint) GetViews() int64 {
	if x != nil {
		return x.Views
	}
	return 0
}

var File_analytics_proto protoreflect.FileDescriptor

const file_analytics_proto_rawDesc = "" +
	"\n" +
	"\x0fanalytics.proto\x12\tanalytics\"J\n" +
	"\x10PostStatsRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12\x1d\n" +
	"\n" +
	"time_range\x18\x02 \x01(\tR\ttimeRange\"\xb8\x01\n" +
	"\x11PostStatsResponse\x12\x14\n" +
	"\x05views\x18\x01 \x01(\x03R\x05views\x12'\n" +
	"\x0funique_visitors\x18\x02 \x01(\x03R\x0euniqueVisitors\x12)\n" +
	"\x11avg_read_time_sec\x18\x03 \x01(\x01R\x0eavgReadTimeSec\x129\n" +
	"\n" +
	"chart_data\x18\x04 \x03(\v2\x1a.analytics.TimeSeriesPointR\tchartData\"P\n" +
	"\x12AuthorStatsRequest\x12\x1b\n" +
	"\tauthor_id\x18\x01 \x01(\tR\bauthorId\x12\x1d\n" +
	"\n" +
	"time_range\x18\x02 \x01(\tR\ttimeRange\"\xc1\x01\n" +
	"\x13AuthorStatsResponse\x12\x1f\n" +
	"\vtotal_views\x18\x01 \x01(\x03R\n" +
	"totalViews\x12%\n" +
	"\x0etotal_visitors\x18\x02 \x01(\x03R\rtotalVisitors\x121\n" +
	"\x15overall_avg_read_time\x18\x03 \x01(\x01R\x12overallAvgReadTime\x12/\n" +
	"\ttop_posts\x18\x04 \x03(\v2\x12.analytics.TopPostR\btopPosts\"N\n" +
	"\aTopPost\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05views\x18\x03 \x01(\x03R\x05views\"E\n" +
	"\x0fTimeSeriesPoint\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x14\n" +
	"\x05views\x18\x02 \x01(\x03R\x05views2\xae\x01\n" +
	"\x10AnalyticsService\x12I\n" +
	"\fGetPostStats\x12\x1b.analytics.PostStatsRequest\x1a\x1c.analytics.PostStatsResponse\x12O\n" +
	"\x0eGetAuthorStats\x12\x1d.analytics.AuthorStatsRequest\x1a\x1e.analytics.AuthorStatsResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_analytics_proto_rawDescOnce sync.Once
	file_analytics_proto_rawDescData []byte
)

func file_analytics_proto_rawDescGZIP() []byte {
	file_analytics_proto_rawDescOnce.Do(func() {
		file_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analytics_proto_rawDesc), len(file_analytics_proto_rawDesc)))
	})
	return file_analytics_proto_rawDescData
}

var file_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_analytics_proto_goTypes = []any{
	(*PostStatsRequest)(nil),    // 0: analytics.PostStatsRequest
	(*PostStatsResponse)(nil),   // 1: analytics.PostStatsResponse
	(*AuthorStatsRequest)(nil),  // 2: analytics.AuthorStatsRequest
	(*AuthorStatsResponse)(nil), // 3: analytics.AuthorStatsResponse
	(*TopPost)(nil),             // 4: analytics.TopPost
	(*TimeSeriesPoint)(nil),     // 5: analytics.TimeSeriesPoint
}
var file_analytics_proto_depIdxs = []int32{
	5, // 0: analytics.PostStatsResponse.chart_data:type_name -> analytics.TimeSeriesPoint
	4, // 1: analytics.AuthorStatsResponse.top_posts:type_name -> analytics.TopPost
	0, // 2: analytics.AnalyticsService.GetPostStats:input_type -> analytics.PostStatsRequest
	2, // 3: analytics.AnalyticsService.GetAuthorStats:input_type -> analytics.AuthorStatsRequest
	1, // 4: analytics.AnalyticsService.GetPostStats:output_type -> analytics.PostStatsResponse
	3, // 5: analytics.AnalyticsService.GetAuthorStats:output_type -> analytics.AuthorStatsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_analytics_proto_init() }
func file_analytics_proto_init() {
	if File_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analytics_proto_rawDesc), len(file_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analytics_proto_goTypes,
		DependencyIndexes: file_analytics_proto_depIdxs,
		MessageInfos:      file_analytics_proto_msgTypes,
	}.Build()
	File_analytics_proto = out.File
	file_analytics_proto_goTypes = nil
	file_analytics_proto_depIdxs = nil
}
